name: Flutter CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload to Firebase App Distribution
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:504128417881:android:7141548a77bf79ded58148
